### ISSUE TITLE
After yarn upgrade @shoutem/ui React Native Package throws EISDIR Exception

### ISSUE THREAD

**Issue by aswinmohanme** [shoutem/ui#227]
I upgraded shoutem/ui to the latest release 0.13, but after upgrading when I ran `react-native start` to start the packager it throws an Error Message.

```
error: bundling: Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:517:19)
    at ConfigChainBuilder.addConfig (/home/aswinmohanme/Projects/Android/SaveGram/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
    at ConfigChainBuilder.findConfigs (/home/aswinmohanme/Projects/Android/SaveGram/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:102:30)
    at buildConfigChain (/home/aswinmohanme/Projects/Android/SaveGram/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/home/aswinmohanme/Projects/Android/SaveGram/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at File.initOptions (/home/aswinmohanme/Projects/Android/SaveGram/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/aswinmohanme/Projects/Android/SaveGram/node_modules/babel-core/lib/transformation/file/index.js:135:24)
TransformError: /home/aswinmohanme/Projects/Android/SaveGram/node_modules/react/react.js: EISDIR: illegal operation on a directory, read
Bundling `index.android.js`  59.4% (47/61), failed.

```

Here is my `package.json`
```
{
	"name": "SaveGram",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"@shoutem/ui": "^0.13.0",
		"package.json": "^2.0.1",
		"react": "16.0.0-alpha.6",
		"react-native": "0.43.2",
		"react-native-fetch-blob": "^0.10.4",
		"react-navigation": "https://github.com/react-community/react-navigation.git"
	},
	"devDependencies": {
		"babel-jest": "19.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "19.0.2",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}


```

**Comment by aswinmohanme** [comment]
I have also done `yarn upgrade` but didn't fix the Issue

**Comment by SoHotSoup** [comment]
@aswinmohanme and when you downgrade to v0.12.0 it works?

**Comment by aswinmohanme** [comment]
Nop, Still shows the same Exact Error. I removed node_modules reinstalled everthing and still no avail.

**Comment by aswinmohanme** [comment]
But No issues on a fresh react-native init

**Comment by SoHotSoup** [comment]
Could you send me your project structure? This seems to be more an issue with the packager than with Shoutem UI.

**Comment by aswinmohanme** [comment]
Yep it was a Problem with the Packager itself. I ditched everything and wrote the project from Scratch. That seemed to fix the Issue. Thanks.

P.S Doing a great job guys, Keep it up :D
