### ISSUE TITLE
Linking Problem

### ISSUE THREAD

**Issue by nanaaikinson24** [shoutem/ui#414]
After I install shoutem UI, run yarn install to install all dependencies,

 react-native link takes forever linking..

**Comment by jmporchet** [comment]
Does it at least complete successfully?

**Comment by nanaaikinson24** [comment]
Yes. But doesn't exit the linking.

**Comment by yeltsinxyz** [comment]
I'm having the same problem.

`yarn add @shoutem/ui` then
`yarn` then
`react-native link`

Throw me this error:

```PS C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact> react-native link
[@shoutem/ui] - linking native dependencies
rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'pbxprojPath' of null

TypeError: Cannot read property 'pbxprojPath' of null
    at Object.linkAssetsIOS [as copyAssets] (C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\ios\copyAssets.js:24:41)
    at C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\link.js:104:12
    at Array.forEach (<anonymous>)
    at linkAssets (C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\link.js:94:28)
    at C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\link.js:171:30

child_process.js:656
    throw err;
    ^

Error: Command failed: node node_modules/react-native/local-cli/cli.js link react-native-vector-icons && node node_modules/react-native/local-cli/cli.js link react-native-linear-gradient && node node_modules/react-native/local-cli/cli.js link react-native-share && node node_modules/react-native/local-cli/cli.js link
react-native-photo-view
rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'pbxprojPath' of null

TypeError: Cannot read property 'pbxprojPath' of null
    at Object.linkAssetsIOS [as copyAssets] (C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\ios\copyAssets.js:24:41)
    at C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\link.js:104:12
    at Array.forEach (<anonymous>)
    at linkAssets (C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\link.js:94:28)
    at C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\link\link.js:171:30


    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\@shoutem\ui\scripts\link.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\core\makeCommand.js:32
throw new Error("Error occurred during executing \""+command+"\" command");
^

Error: Error occurred during executing "node ./node_modules/@shoutem/ui/scripts/link.js" command
    at ChildProcess.prelink (C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact\node_modules\react-native\local-cli\core\makeCommand.js:32:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
PS C:\Bitnami\wampstack-7.1.25-0\apache2\htdocs\LubaReact>```

**Comment by getmonetapp** [comment]
I have the same error as above. Same repro steps

**Comment by alxmiron** [comment]
I have the same error as above. Same repro steps

**Comment by Pratikkakkad** [comment]
is there any solution for this?

**Comment by floscom** [comment]
Same here

**Comment by kairon-v** [comment]
I have the same problem

**Comment by jmporchet** [comment]
The last commit on this repo was Nov 5th, so it's pretty unmaintained. One way to move forward is if someone wants to go ahead and fork the repo with a fix. Another one is to just change component library altogether.

By the way, GIthub added reactions to comments, so the +1 reaction to @yeltsinxyz would be preferable. This way the thread doesn't get cluttered.

**Comment by ckOfor** [comment]
I am having linking problem

yarn add @shoutem/ui then
yarn then
react-native link

```\[@shoutem/ui] - linking native dependencies
error Failed to get dependency config
child_process.js:661
    throw err;
    ^

Error: Command failed: node node_modules/react-native/local-cli/cli.js link react-native-vector-icons && node node_modules/react-native/local-cli/cli.js link react-native-linear-gradient && node node_modules/react-native/local-cli/cli.js link react-native-share && node node_modules/react-native/local-cli/cli.js link react-native-photo-view
error Failed to get dependency config

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:658:13)
    at Object.<anonymous> (/Users/oforchinedu/Documents/Biscayne/Biscayne-ios/Biscayne-ios/node_modules/@shoutem/ui/scripts/link.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
/Users/oforchinedu/Documents/Biscayne/Biscayne-ios/Biscayne-ios/node_modules/@react-native-community/cli/build/tools/getHooks.js:37
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node ./node_modules/@shoutem/ui/scripts/link.js" command
    at ChildProcess.commandProcess.on.code (/Users/oforchinedu/Documents/Biscayne/Biscayne-ios/Biscayne-ios/node_modules/@react-native-community/cli/build/tools/getHooks.js:37:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)```

**Comment by rodrigobutta** [comment]
Same of all above. It might came unmainained now. Sad.

![image](https://user-images.githubusercontent.com/203718/57197102-85caf300-6f39-11e9-9f1e-4baa99f78aa8.png)

**Comment by dev-mikhail** [comment]
I am also sad.
I created a react native project with the latest version.
   react-native version: "0.61.1"
   react version: "16.9.0"

executing the command below: (@shoutem/ui version: 1.0.1)
     react-native install @shoutem/ui

there are some link errors.
then how can I solve it?
