### ISSUE TITLE
react-native link issue with RN 0.59

### ISSUE THREAD

**Issue by motogod** [shoutem/ui#425]
"dependencies": {
    "@shoutem/ui": "^0.23.16",
    "react": "16.8.3",
    "react-native": "0.59.0",
    "react-native-photo-view": "^1.5.2",
    "react-native-vector-icons": "^6.4.1",
  },

Step1:
`react-native init newProject` 

Step2:
`npm install --save react-native-vector-icons`
`react-native link react-native-vector-icons`
and copy the file data `/nodemule/react-native-vector-icons/Fonts` into `android/app/src/main/assets/fonts`

`npm install --save react-native-photo-view`
`react-native link react-native-photo-view`

Step3:
Just fllow the tutorial 

Install @shoutem/ui in your project:
`npm install --save @shoutem/ui`
`react-native link @shoutem/ui`

It will show the error:
```
[@shoutem/ui] - linking native dependencies
error Failed to get dependency config
child_process.js:662
    throw err;
    ^

Error: Command failed: node node_modules/react-native/local-cli/cli.js link react-native-vector-icons && node node_modules/react-native/local-cli/cli.js link react-native-linear-gradient && node node_modules/react-native/local-cli/cli.js link react-native-share && node node_modules/react-native/local-cli/cli.js link react-native-photo-view
error Failed to get dependency config

    at checkExecSyncError (child_process.js:622:11)
    at execSync (child_process.js:659:13)
    at Object.<anonymous> (/Users/morton.hsu/ReactNativeProject/test59/node_modules/@shoutem/ui/scripts/link.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
/Users/morton.hsu/ReactNativeProject/test59/node_modules/@react-native-community/cli/build/tools/getHooks.js:37
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node ./node_modules/@shoutem/ui/scripts/link.js" command
    at ChildProcess.commandProcess.on.code (/Users/morton.hsu/ReactNativeProject/test59/node_modules/@react-native-community/cli/build/tools/getHooks.js:37:15)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

Any things what should we do ?

**Comment by motogod** [comment]
fix it. Still have to type:
```
npm install react-native-share --save
react-native link react-native-share
```

**Comment by imondal007** [comment]
How did you fix it?

**Comment by motogod** [comment]
https://github.com/shoutem/ui/issues/425#issuecomment-472677167

Imran Mondal <notifications@github.com> 於 2019年5月11日 週六 下午2:55寫道：

**Comment by cyb3rsalih** [comment]
Re-install and re-link package solved my problem.

**Comment by goneale** [comment]
Yes, well that didn't solve my problem.
npm install @aws-amplify/pushnotification --save
then
react-native link @aws-amplify/pushnotification
results in error:
```
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
debug Package to link: @aws-amplify/pushnotificaton
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/Users/goneale/Projects/rag-apps/WowApps/WowManager/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (/Users/goneale/Projects/rag-apps/WowApps/WowManager/node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
```

**Comment by ffMathy** [comment]
I needed to run `npm install`.
