### ISSUE TITLE
Error when react-native link

### ISSUE THREAD

**Issue by 1quintana** [shoutem/ui#427]
``` bash
warn Group 'Resources' does not exist in your Xcode project. We have created it automatically for you.
error Failed to get dependency config
child_process.js:656
    throw err;
    ^

Error: Command failed: node node_modules/react-native/local-cli/cli.js link react-native-vector-icons && node node_modules/react-native/local-cli/cli.js link react-native-linear-gradient && node node_modules/react-native/local-cli/cli.js link react-native-share && node node_modules/react-native/local-cli/cli.js link react-native-photo-view
warn Group 'Resources' does not exist in your Xcode project. We have created it automatically for you.
error Failed to get dependency config

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (/Users/lquintana/Projects/ReactHelloWorld/node_modules/@shoutem/ui/scripts/link.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
/Users/lquintana/Projects/ReactHelloWorld/node_modules/@react-native-community/cli/build/tools/getHooks.js:37
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node ./node_modules/@shoutem/ui/scripts/link.js" command
    at ChildProcess.commandProcess.on.code (/Users/lquintana/Projects/ReactHelloWorld/node_modules/@react-native-community/cli/build/tools/getHooks.js:37:15)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

```

**Comment by motogod** [comment]
Duplicated with my question #425 , although I don't know why I have to install `react-native-share`

Hope my solution can help you.
