### ISSUE TITLE
Unable to resolve module `./components/RichMedia`

### ISSUE THREAD

**Issue by TarzanWD** [shoutem/ui#444]
After moving to version 1.0.0, React Native cant build package:
```
error: bundling failed: Error: Unable to resolve module `./components/RichMedia` from `C:\Users\...\node_modules\@shoutem\ui\index.js`: The module `./components/RichMedia` could not be found from `C:\Users\...\node_modules\@shoutem\ui\index.js`. Indeed, none of these files exist:
  * `C:\Users\...\node_modules\@shoutem\ui\components\RichMedia(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Users\...\node_modules\@shoutem\ui\components\RichMedia\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (C:\Users\...\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\...\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\...\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (C:\Users\...\node_modules\metro\src\lib\transformHelpers.js:264:42)
    at dependencies.map.result (C:\Users\...\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\...\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at C:\Users\...\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\...\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
```

I can't find any imports in index.js, neither any imports in my project, but still, this shows up.
I tried to reinstall node_modules and clean RN cache, but nothing has worked.

Is there any other place, where it could be cached or is this somehow related to the upgrade?

The project was created with create-react-app --typescript
react-native: 0.60.4
react: 16.8.6

**Comment by aesqe** [comment]
@TarzanWD can you confirm that your project works fine with an earlier version of @shoutem/ui?

**Comment by tmaly1980** [comment]
I'm experiencing this too, I've run watchman watch-del-all, cleaned the cache, cleaned the xcode project, etc and no help.
