### ISSUE TITLE
Restaurant example app invalid regular expression error

### ISSUE THREAD

**Issue by psrdotcom** [shoutem/ui#458]
Not able to run the app and in console the following error is being displayed
"error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details."

**Comment by psrdotcom** [comment]
When I use verbose, the following error details has been displayed

> error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
debug SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\SureshRajuPilli\Documents\PSR\Dev\Shoutem\ui\examples\RestaurantsApp\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (C:\Users\SureshRajuPilli\Documents\PSR\Dev\Shoutem\ui\examples\RestaurantsApp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:61:59)
    at getDefaultConfig (C:\Users\SureshRajuPilli\Documents\PSR\Dev\Shoutem\ui\examples\RestaurantsApp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:75:20)
    at load (C:\Users\SureshRajuPilli\Documents\PSR\Dev\Shoutem\ui\examples\RestaurantsApp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:103:25)
    at Object.runServer [as func] (C:\Users\SureshRajuPilli\Documents\PSR\Dev\Shoutem\ui\examples\RestaurantsApp\node_modules\@react-native-community\cli\build\commands\server\runServer.js:72:58)
    at C:\Users\SureshRajuPilli\Documents\PSR\Dev\Shoutem\ui\examples\RestaurantsApp\node_modules\@react-native-community\cli\build\cliEntry.js:152:22
